---
name: Docker build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
    branches: [main]
    paths:
      - '**.go'
      - '**/**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/dockerbuild.yml'
      - 'Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - '**/**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/dockerbuild.yml'
      - 'Dockerfile'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, commit, or tag to checkout'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  docker-build-and-push:
    runs-on: ubuntu-latest
    #runs-on: [self-hosted]
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      -
        name: Set up Docker Context for Buildx
        run: docker context create builders
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4
        with:
          endpoint: builders
      -
        name: Log in to container register
        id: login-ghcr
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=sha,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,event=pr
      -
        name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
